# Generated by Django 4.2.28 on 2026-02-12 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
