# Generated by Django 4.2.28 on 2026-04-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['name'], name='main_room_name_c7d4bd_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['topic'], name='main_room_topic_i_507413_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['host'], name='main_room_host_id_504d41_idx'),
        ),
    ]
